# Site settings
title: "0x375"
email: "info@0x375.org"
description: "Welcome to the home of 0x375"
baseurl: ""
url: "https://0x375.org"
twitter_username: jekyllrb
github_username:  jekyll
collections:
  events:
    output: true

# Build settings
markdown: kramdown
exclude: [vendor]
